---
- hosts: ubuntu
  gather_facts: false
  become: true
  tasks:
   - name: deploy apache
     shell: apt-get install -y apache2

   - name: Install PHP7
     shell: apt-get install -y php-fpm php-mbstring php-pdo php-intl php-gd php-mcrypt php-memcached php-xml php-zip php-opcache libapache2-mod-php7.0 php-mysql

   - name: download wordpress
     shell: cd /var/www &&  wget https://fr.wordpress.org/wordpress-4.9.2-fr_FR.tar.gz

   - name: extract wordpress.tar.gz
     shell: cd /var/www && tar -xvf wordpress-4.9.2-fr_FR.tar.gz

   #- name: rename the folder wordpress/ into blog/
   #  shell: cd /var/www && mv wordpress/ blog/

   - name: enable services
     shell: systemctl restart apache2 php7.0-fpm

   - name: rename the folder and move it and set chmod 777
     shell: cd /var/www && mv wordpress/ blog/
     shell: cd /var/www && chmod 777 blog
     shell: cd /var/www/blog && cp wp-config.sample.php wp-config.php

   - name: edit setup-config Wordpress php (database parameters)
     shell: cd /var/www/html/blog && grep -i 'votre_nom_de_bdd' wp-config.php | sed -i 's/votre_nom_de_bdd/wordpress_db/g' wp-config.php
     shell: cd /var/www/html/blog && grep -i 'votre_utilisateur_de_bdd' wp-config.php | sed -i 's/votre_utilisateur_de_bdd/imad/g' wp-config.php
     shell: cd /var/www/html/blog && grep -i 'votre_mdp_de_bdd' wp-config.php | sed -i 's/votre_mdp_de_bdd/insta75005/g' wp-config.php
     shell: cd /var/www/html/blog && grep -i 'localhost' wp-config.php | sed -i 's/localhost/toto/g' wp-config.php

