---
- hosts: ubuntu
  gather_facts: false
  become: true
  become_method: sudo
  become_user: root
  tasks:
   - name: Install haproxy
     apt: update_cache=yes cache_valid_time=3600
     apt: name=haproxy state=present
    
   - name: Enable init script
     replace: dest='/etc/default/haproxy' 
     replace: regexp='ENABLED=0'
     replace: replace='ENABLED=1'
     
   - name: configure haproxy
     shell: cd / && mkdir templates && touch templates/haproxy.cfg
     shell: echo "global
            log 127.0.0.1 local0 notice
            maxconn 2000
            user haproxy
            group haproxy

            defaults
            log     global
            mode    http
            option  httplog
            option  dontlognull
            retries 3
            option redispatch
            timeout connect  5000
            timeout client  10000
            timeout server  10000

            listen {{haproxy_app_name}} 0.0.0.0:80
            mode {{haproxy_mode}}
            stats {{haproxy_enable_stats}}
            {% if haproxy_enable_stats == 'enable' %}
            stats uri /haproxy?stats
            stats realm Strictly\ Private
            {% for user in haproxy_stats_users %}
            stats auth {{user.username}}:{{user.password}}
            {% endfor %}
            {% endif %}
            balance {{haproxy_algorithm}}
            option httpclose
            option forwardfor
            {% for server in haproxy_backend_servers %}
            server {{server.name}} {{server.ip}}:{{server.port}} {{server.paramstring}}
            {% endfor %}"
            " >> templates/haproxy.cfg
            
vars:
  haproxy_app_name: myapp
  haproxy_mode: http
  haproxy_enable_stats: enable 
  haproxy_algorithm: roundrobin
  haproxy_backend_servers: 
    - {name: server1, ip: 184.72.114.49, port: 80, paramstring: cookie A check}
    - {name: server2, ip: 54.167.217.36, port: 80, paramstring: cookie A check}
    
        - name: remplace haproxy.cfg
          shell: cd / && cp templates/haproxy.cfg /etc/haproxy/haproxy.cfg